// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: SquareLine_Project

#include "../ui.h"
#include "app_obd_dsp/locked_boot.h"

void ui_ScreenPageLogo_screen_init(void)
{
    ui_ScreenPageLogo = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_ScreenPageLogo, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_ScreenPageLogo, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_ScreenPageLogo, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    // the Racing My Car logo on black (images/imgBootLogoCustom.c)
    LV_IMG_DECLARE(imgBootLogoCustom);
    imageLogo = lv_img_create(ui_ScreenPageLogo);
    lv_img_set_src(imageLogo, &imgBootLogoCustom);
    lv_obj_align(imageLogo, LV_ALIGN_CENTER, 0, 0);
    lv_obj_add_event_cb(ui_ScreenPageLogo, ui_event_logo_background, LV_EVENT_ALL, NULL);

    // Racing My Car locked boot animation plays on top of the logo at every power-on (see locked_boot.h).
    locked_boot_start(ui_ScreenPageLogo);
}

