// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ
// The UI theme is named PINK_CAT (pink cat): main color pink, secondary color purple
#include "ui.h"
#include "screens/ui_menu.h"
#include "ui_helpers.h"
#include "ui_ext.h"
#include "ui_disp_item.h"
#include "ui_theme.h"
#include "theme_engine/theme_interface.h"
#include "app_obd_dsp/app_event.h"
#include "app_obd_dsp/obd_data_cache.h"
#include <driver/gpio.h>
#include "bsp_obd_dsp/bsp_board.h"
#include "bsp_obd_dsp/nvs_storage.h"
#include "bsp_obd_dsp/lcd_driver/ST77916.h"
#include "bsp_obd_dsp/elm327_ble_client.h"
#include "bsp_obd_dsp/espnow_link.h"
#include "bsp_obd_dsp/gauge_pair_ble_client.h"
#include "bsp_obd_dsp/racechrono_ble_diy.h"
#include "app_obd_dsp/vehicle_profiles.h"
#include "app_obd_dsp/boot_block_player.h"
#include "app_obd_dsp/boot_media_mount.h"
#include "app_obd_dsp/locked_boot.h"
#include "app_obd_dsp/ota_wifi_server.h"
#include "esp_system.h"
#include "esp_random.h"
#include "esp_log.h"
#include "esp_idf_version.h"
#include "esp_timer.h"
#include <stdio.h>
#include <stdint.h>
#include <string.h>


static const char *TAG = "ui";
///////////////////// VARIABLES ////////////////////
void ui_ScreenPageLogo_screen_init(void);
lv_obj_t * ui_ScreenPageLogo;
lv_obj_t * imageLogo;
lv_obj_t * imageEasterEgg;

// SCREEN: ui_ScreenPageThemeGauge (the gauge: pages of the theme in the theme partition, theme_engine/)
void ui_ScreenPageThemeGauge_screen_init(void);
lv_obj_t * ui_ScreenPageThemeGauge;
void ui_event_theme_gauge_background(lv_event_t * e);
uint8_t ui_theme_gauge_page_index = 0;  // Current theme page index

// SCREEN: ui_ScreenPageEasterEgg (VERSION)
void ui_ScreenPageEasterEgg_screen_init(void);
lv_obj_t * ui_ScreenPageEasterEgg;
lv_obj_t * ui_LabelEasterEggInfo;

// SCREEN: ui_ScreenPageBLEScan (OBD)
void ui_ScreenPageBLEScan_screen_init(void);
lv_obj_t * ui_ScreenPageBLEScan;

// SCREEN: ui_ScreenPageOTAMode (UPDATE)
void ui_ScreenPageOTAMode_screen_init(void);
void ui_ota_mode_refresh(void);

///////////////////// TEST LVGL SETTINGS ////////////////////
/* ---- Gauge sweep animation ----
   In ui_ext.c; the SWEEP_* constants live in ui_ext.h and the sweep state
   machine is driven via ui_ext_sweep_active()/ui_ext_sweep_get_step()/ui_ext_sweep_tick(). */

// RPM warning flash (test ticks, strobe, linked ramp) migrated to ui_ext.c — see ui_ext_rpm_flash_tick()

// LVGL task handle (set by app_main); priority is temporarily raised to own the CPU while flashing
TaskHandle_t g_lvgl_task_handle = NULL;

// ===== Boot-video state =====
// Moved to ui_ext.c (see ui_ext_boot_video_tick / ui_ext_intro_tick).

// (boot_video_timer_cb moved to ui_ext.c)

// (ui_sweep_get_step / ui_intro_* accessors moved to ui_ext.c)

static uint32_t ui_refresh_period_ms_for_screen(lv_obj_t *scr,
                                                bool in_sweep,
                                                bool rpm_flashing,
                                                bool rpm_link_ramp)
{
    if (in_sweep) {
        return SWEEP_TICK_MS;
    }
    if (rpm_flashing) {
        return RPM_FLASH_PERIOD_MS;
    }
    if (rpm_link_ramp) {
        return 16;
    }

    if (scr == ui_ScreenPageThemeGauge) {
        return 16;
    }
    if (scr == ui_ScreenPageLogo) {
        return 33;
    }
    if (scr == ui_ScreenPageBLEScan || scr == ui_ScreenPageOTAMode || scr == ui_ScreenPageEasterEgg) {
        return 200;
    }
    return 50;
}

static bool ui_screen_updates_live_data(lv_obj_t *scr)
{
    return scr == ui_ScreenPageThemeGauge;
}

// Converts the core firmware's live OBD snapshot into the ABI-stable struct
// theme_engine consumes, applying the unit conversions the two structs don't
// share (boost 0.1bar->0.01bar, oil pressure bar->PSI, battery mV->0.1V) and
// clamping into the narrower target field widths. Invalid-sentinel fields are
// passed through as 0 rather than propagating e.g. -32768 into a uint8_t.
static void ui_build_theme_snapshot(obd_snapshot_t *out,
                                     int16_t clt, int16_t oil, int16_t oilp_x10,
                                     int32_t bat_mv, int16_t boost_x10, int16_t afr_x100,
                                     uint16_t usRpm, uint16_t ucSpeed, int16_t tps,
                                     enGear eGear, bool gear_unknown)
{
    memset(out, 0, sizeof(*out));
    out->rpm = usRpm;
    out->speed = (ucSpeed > 255) ? 255 : (uint8_t)ucSpeed;
    out->boost = (boost_x10 <= -32768) ? 0 : (int16_t)(boost_x10 * 10);
    out->coolant_temp = (clt < 0) ? 0 : (clt > 255 ? 255 : (uint8_t)clt);
    if (oilp_x10 < 0) {
        out->oil_pressure = 0;
    } else {
        int32_t psi = (int32_t)(oilp_x10 * 1.45038f / 10.0f + 0.5f);
        out->oil_pressure = (psi > 255) ? 255 : (uint8_t)psi;
    }
    out->gear = gear_unknown ? (int8_t)127 : (int8_t)eGear;
    if (bat_mv < 0) {
        out->battery_voltage = 0;
    } else {
        int32_t dv = bat_mv / 100;
        out->battery_voltage = (dv > 255) ? 255 : (uint8_t)dv;
    }
    out->oil_temp = (oil < 0) ? 0 : (oil > 255 ? 255 : (uint8_t)oil);
    out->afr = (afr_x100 < 0) ? 0 : (uint16_t)afr_x100;
    out->throttle = (tps < 0) ? 0 : (tps > 100 ? 100 : (uint8_t)tps);

    int16_t iat = obd_data_get_intake_temp();
    out->intake_temp = (iat < 0) ? 0 : (iat > 255 ? 255 : (uint8_t)iat);
    int16_t load = obd_data_get_load_pct();
    out->load = (load < 0) ? 0 : (load > 100 ? 100 : (uint8_t)load);
    for (int i = 0; i < OBD_EXT_COUNT && i < (int)(sizeof(out->ext) / sizeof(out->ext[0])); i++) {
        int32_t v = obd_data_get_ext((obd_ext_t)i);
        out->ext[i] = v;   // OBD_EXT_INVALID (INT32_MIN) when the car does not give it: the theme shows "-"
    }
}

void my_timerMain(lv_timer_t * timer)
{
    // ---- Process the event queue (ESP-NOW / BLE cross-task events) ----
    {
        app_event_t evt;
        while (app_event_recv(&evt)) {
            switch (evt.type) {
                case APP_EVT_ESPNOW_SYNC_SLOT:
                    ui_sweep_set_from_sync((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_INTRO_STEP:
                    ui_intro_set_step((int)evt.data.u8);
                    break;
                case APP_EVT_ESPNOW_THRESH_SYNC:
                    // RPM threshold synced from another gauge: write local NVS (the master forwards it to the other slaves) + refresh this page
                    espnow_link_apply_synced_threshold((uint16_t)evt.data.u16);
                    break;
                default:
                    break;
            }
        }
    }

    static uint16_t usRpm = 0;
    static uint16_t ucSpeed = 0;  // uint16_t so sweep can reach 999
    static enGear eGear = GEAR_NEUTRAL;
    static bool  s_gear_unknown = false;   // OBD-gear profile can't read a valid gear → show "--" (no ratio-calc fallback)
    // rpm flash state (red/black toggle, strobing flag, linked ramp) moved to ui_ext.c
    // Sweep animation detection; sweep state lives in ui_ext.c now
    #define IN_SWEEP (ui_ext_sweep_active())
    static uint8_t ucOnlyOnce = 0;
    static uint32_t ulOpenLightTimeCnt = 0;

    const nvs_user_cfg_t *user_cfg = nvs_cfg_get();
    int16_t clt = 0;
    int16_t oil = 0;
    int16_t oilp_x10 = 0;
    int16_t tps = 0;
    int32_t bat_mv = 0;
    int16_t boost_x10 = 0;
    int16_t afr_x100 = 0;

    /* ---- Sweep trigger ----
       Master: triggered the instant the ELM327 BLE connects and advances the animation itself;
       Slave: never self-triggers, driven by the master's broadcast sweep_step (espnow recv → app_event queue). */
    bool is_slave = (user_cfg->device_role == ESPNOW_ROLE_SLAVE);
    // "connected" signal: slave=master data being received, master=ELM327 BLE connected (shared by status display and the master's sweep trigger)
    bool ble_now = is_slave ? espnow_link_slave_has_data() : elm327_ble_is_connected();
    ui_ext_sweep_trigger(ble_now, is_slave);

    lv_obj_t *scr = lv_scr_act();
    bool live_data_screen = ui_screen_updates_live_data(scr);
    bool rpm_warn_possible = ui_ext_rpm_warn_possible();

    if (!IN_SWEEP && (live_data_screen || rpm_warn_possible || ui_ext_rpm_is_flashing() || ui_ext_rpm_link_ramp_active())) {
        obd_data_snapshot_t obd;

        obd_data_get_snapshot(&obd);
        clt       = obd.coolant_temp;
        oil       = obd.oil_temp;      // real oil temperature °C (SSM 22 10 17), -100=invalid
        oilp_x10  = obd.oil_pressure_x10; // oil pressure 0.1bar, -1=invalid
        tps       = obd.tps;
        bat_mv    = obd.bat_mv;
        boost_x10 = obd.boost_x10; // boost gauge pressure 0.1bar, -32768=invalid
        afr_x100  = obd.afr_x100;   // air-fuel ratio ×100, -1=invalid
        usRpm     = obd.rpm;
        ucSpeed   = obd.speed;
        int8_t decoded_gear = obd.gear;
        if (decoded_gear >= 0 && decoded_gear <= GEAR_8) {
            eGear = (enGear)decoded_gear;
            s_gear_unknown = false;
        } else if (vehicle_profile_get_active()->obd_gear_did != 0 || vehicle_profile_get_active()->methods[MV_GEAR].count != 0 ||
                   vehicle_profile_get_active()->gear_count == 0) {
            // gear read from the car (or a profile without ratios): no RPM/speed guessing, "--" until a valid gear arrives
            s_gear_unknown = true;
        } else {
            eGear = calculate_gear(usRpm, ucSpeed);
            s_gear_unknown = false;
        }
    }

    /* ---- Data source: sweep or real OBD (sweep state machine moved to ui_ext.c) ---- */
    float sweep_ratio = ui_ext_sweep_tick(is_slave, user_cfg->brightness_day);
    if (sweep_ratio >= 0.0f) {
        usRpm   = (uint16_t)(SWEEP_RPM_PEAK * sweep_ratio);
        ucSpeed = (uint16_t)(SWEEP_SPEED_PEAK * sweep_ratio); // uint16_t so it can hold 999
        eGear   = (enGear)((int)(6.0f * sweep_ratio + 0.5f)); // up to 6th gear
        s_gear_unknown = false;
        // the theme page (ui_build_theme_snapshot below) forwards these locals as-is, so without this they'd stay
        // frozen at the 0 they were declared with above (real OBD reads are skipped while IN_SWEEP).
        clt       = (int16_t)disp_item_sweep_value(DISP_ITEM_CLT, sweep_ratio);
        oil       = (int16_t)disp_item_sweep_value(DISP_ITEM_OIL, sweep_ratio);
        oilp_x10  = (int16_t)disp_item_sweep_value(DISP_ITEM_OILP, sweep_ratio);
        bat_mv    = disp_item_sweep_value(DISP_ITEM_BAT, sweep_ratio);
        boost_x10 = (int16_t)disp_item_sweep_value(DISP_ITEM_BOOST, sweep_ratio);
        afr_x100  = (int16_t)disp_item_sweep_value(DISP_ITEM_AFR, sweep_ratio);
        tps       = (int16_t)disp_item_sweep_value(DISP_ITEM_TPS, sweep_ratio);
    }
    /* Extra data (fuel level, trims, ...) is asked of the car only while a theme page shows it */
    obd_data_set_wanted_local(scr == ui_ScreenPageThemeGauge ? theme_wanted_ext_mask() : 0);
    /* Theme-provided gauge page: feed the theme engine's arc/bar/label bindings */
    if (scr == ui_ScreenPageThemeGauge) {
        obd_snapshot_t theme_snap;
        ui_build_theme_snapshot(&theme_snap, clt, oil, oilp_x10, bat_mv, boost_x10, afr_x100,
                                 usRpm, ucSpeed, tps, eGear, s_gear_unknown);
        theme_update_data(&theme_snap);
    }
    /* Device info page: role and OBD link (screens/ui_ScreenPageEasterEgg.c) */
    if (scr == ui_ScreenPageEasterEgg) ui_device_info_refresh();

    /* OTA mode screen: refresh connection status */
    ui_ota_mode_refresh();

#if EXAMPLE_PIN_NUM_BK_LIGHT >= 0
        //wait 500ms before turning on the backlight, so it isn't enabled before init completes; runs once
        if(ucOnlyOnce == 0)
        {
            ulOpenLightTimeCnt++;
            if(ulOpenLightTimeCnt > 400 / 200)
            {
                uint8_t bright = user_cfg->brightness_day;
                if(bright < 10) bright = 100;
                Set_Backlight(bright);
                ESP_LOGD(TAG, "Set LCD backlight to %d%%", bright);
                ulOpenLightTimeCnt = 0;
                ucOnlyOnce = 1;//run once only
            }
        }
#endif

    /* The bottom info bar (TRIP/ODO/MAX/AVG/TIME) belonged to the removed Main page and was removed with it.
       Mileage statistics are still accumulated by a background task and can be shown on other pages or re-attached later. */

    /* ===== Video boot mode (INTRO == 2: VIDEO, the boot_block flashed via the phone app) ===== */
    // Moved to ui_ext.c; returns true while the Logo/video is still showing, so my_timerMain returns early.
    // Racing My Car locked boot animation first (compiled into the firmware, not replaceable); the rest of the
    // boot flow — including the owner's boot animation from the app — only starts once it has finished.
    if (!locked_boot_done()) return;
    if (ui_ext_boot_video_tick()) return;

    /* ===== Boot flow: Logo -> theme (ui_ext.c) ===== */
    ui_ext_intro_tick(is_slave);

    /* ---- RPM over-limit flash warning (migrated to ui_ext.c) ---- */
    ui_ext_rpm_flash_tick(usRpm, IN_SWEEP);

    ui_ext_no_signal_update(ble_now);
    ui_ext_doors_update();

    /* ---- Adaptive refresh rate: data pages run fast, static pages stay slow ----
       Only this UI timer's period changes (pure redraw pacing); no OBD/RS485/ESP-NOW query or broadcast is affected. */
    if (timer) {
        static uint32_t s_refresh_ms = 200;
        lv_obj_t *refresh_scr = lv_scr_act();
        uint32_t want_ms = ui_refresh_period_ms_for_screen(refresh_scr, IN_SWEEP, ui_ext_rpm_is_flashing(), ui_ext_rpm_link_ramp_active());
        if (want_ms != s_refresh_ms) {
            s_refresh_ms = want_ms;
            lv_timer_set_period(timer, want_ms);
        }
    }
    #undef IN_SWEEP
}
///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////



///////////////////// FUNCTIONS ////////////////////
void ui_event_logo_background(lv_event_t * e)
{  
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_CLICKED) {
        static uint32_t last_click_tick = 0;
        static uint8_t  click_cnt = 0;
        uint32_t now = lv_tick_get();
        if(now - last_click_tick < 400){
            click_cnt++;
        }else{
            click_cnt = 1;
        }
        last_click_tick = now;


        ESP_LOGD(TAG, "Logo LV_EVENT_CLICKED");
    }   
}

// Shows theme page ui_theme_gauge_page_index in place of the current one, which is freed once the new one is up
// (before, every swipe left the old page in memory until the gauge ran out of it).
static void theme_page_show(void)
{
    lv_obj_t *old = ui_ScreenPageThemeGauge;
    ui_ScreenPageThemeGauge = NULL;
    ui_ScreenPageThemeGauge_screen_init();
    lv_scr_load_anim(ui_ScreenPageThemeGauge, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, old && lv_scr_act() == old);
    if (old && lv_scr_act() != old) lv_obj_del(old);
}

// Theme-provided gauge page: swipe left/right moves to the next/prev page
// declared by the active theme. Swiping left past the last theme page goes
// to the Info page (version/settings). Swiping right from the first theme
// page also goes to Info page (creating a loop: theme pages ↔ Info).
void ui_event_theme_gauge_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        uint8_t page_count = theme_page_list_count();

        if(dir == LV_DIR_LEFT) {
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_theme_gauge_page_index + 1 < page_count) {
                // Move to next theme page
                ui_theme_gauge_page_index++;
                theme_page_show();
            } else {
                // past the last theme page: back to the first (the menu opens only with a swipe up)
                ui_theme_gauge_page_index = 0;
                theme_page_show();
            }
        }
        else if(dir == LV_DIR_TOP) {
            // swipe up → the app menu (screens/ui_menu.c)
            lv_indev_wait_release(lv_indev_get_act());
            ui_menu_open();
        }
        else if(dir == LV_DIR_RIGHT) {
            lv_indev_wait_release(lv_indev_get_act());
            if (ui_theme_gauge_page_index > 0) {
                // Move to previous theme page
                ui_theme_gauge_page_index--;
                theme_page_show();
            } else {
                // before the first theme page: to the last one
                ui_theme_gauge_page_index = page_count ? page_count - 1 : 0;
                theme_page_show();
            }
        }
    }
}
void ui_event_easter_egg_background(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    if(event_code == LV_EVENT_GESTURE) {
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT) {
            // opened from the menu: back to it
            lv_indev_wait_release(lv_indev_get_act());
            ui_menu_open();
        }
        else if(dir == LV_DIR_TOP) {
            // swipe up → BLE scan page
            lv_indev_wait_release(lv_indev_get_act());
            _ui_screen_change(&ui_ScreenPageBLEScan, LV_SCR_LOAD_ANIM_FADE_ON, 5, 0, &ui_ScreenPageBLEScan_screen_init);
        }
        else if(dir == LV_DIR_BOTTOM) {
            // swipe down → the menu's SETTINGS (screens/ui_menu_settings.c)
            lv_indev_wait_release(lv_indev_get_act());
            if (!ui_ScreenPageMenuSettings) ui_ScreenPageMenuSettings_screen_init();
            lv_scr_load_anim(ui_ScreenPageMenuSettings, LV_SCR_LOAD_ANIM_FADE_ON, 200, 0, false);
        }
    }

    // ---- hand-written extension logic hook (ui_ext.c, not overwritten by SquareLine) ----
    ui_ext_tick();
}

// OTA button: enter OTA mode screen (WiFi SoftAP + HTTP server, no BLE)
void ui_event_easter_egg_ota_button(lv_event_t *e)
{
    (void)e;
    _ui_screen_change(&ui_ScreenPageOTAMode, LV_SCR_LOAD_ANIM_FADE_ON, 300, 0, &ui_ScreenPageOTAMode_screen_init);
}

// OTA mode screen: refresh status from the LVGL timer (called every 500ms)
void ui_ota_mode_refresh(void)
{
    if (ui_ScreenPageOTAMode == NULL) return;
    if (ui_LabelOTAModeStatus == NULL) return;

    if (ota_wifi_server_is_busy()) {
        lv_label_set_text(ui_LabelOTAModeStatus, "RECEIVING THE UPDATE...");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0x00CC66), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_READY) {
        lv_label_set_text(ui_LabelOTAModeStatus, "READY: OPEN THE RACING MY CAR APP");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0x00CC66), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_IDLE) {
        lv_label_set_text(ui_LabelOTAModeStatus, "STARTING WI-FI...");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0xAAAAAA), LV_PART_MAIN | LV_STATE_DEFAULT);
    } else if (ota_wifi_server_get_state() == OTA_WIFI_STATE_ERROR) {
        lv_label_set_text(ui_LabelOTAModeStatus, "WI-FI ERROR");
        lv_obj_set_style_text_color(ui_LabelOTAModeStatus, lv_color_hex(0xFF0000), LV_PART_MAIN | LV_STATE_DEFAULT);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    // OPTIMIZATION: Logo is already created and displayed by app_main.c before this function
    // to ensure both Master (with 2MB theme) and Slave show logo simultaneously.
    // Here we only load theme and create other UI elements.

    // Initialize theme partition system AFTER logo is visible
    // This loads the theme from theme_0/theme_1 partition, or falls back to default
    ESP_LOGI(TAG, "Initializing theme partition system");
    esp_err_t theme_ret = theme_engine_init();
    if (theme_ret == ESP_OK) {
        theme_info_t info;
        if (theme_get_info(&info) == ESP_OK) {
            ESP_LOGI(TAG, "Theme loaded: %s v%s by %s", info.name, info.version, info.author);
        }
        // Run test to print detailed theme info
        theme_engine_test();
    } else {
        ESP_LOGW(TAG, "Theme partition system initialization failed, using built-in themes");
    }

    // Load the saved UI theme BEFORE any screen is built, so every screen
    // picks up the active theme's colors at creation time.
    ui_theme_init();

    // the gauge is the theme's pages (ui_menu.c ui_menu_home_screen); they are built when shown
    ui_ScreenPageThemeGauge = NULL;

    lv_timer_create(my_timerMain,
                    ui_refresh_period_ms_for_screen(lv_scr_act(), false, false, false),
                    NULL);
    ui_menu_init();   // a minute idle on the menu pages -> back to the gauge
}

/* BLE scan page events - swipe left returns to the device info page */
void ui_event_ble_scan_background(lv_event_t * e)
{
    lv_event_code_t code = lv_event_get_code(e);
    if(code == LV_EVENT_GESTURE){
        lv_dir_t dir = lv_indev_get_gesture_dir(lv_indev_get_act());
        if(dir == LV_DIR_LEFT || dir == LV_DIR_RIGHT){
            // on this page slaves run the pairing scan (gauge_pair_ble), not the OBD scan (elm327_ble); stop the matching one when swiping away.
            if (nvs_cfg_get()->device_role == ESPNOW_ROLE_SLAVE) {
                gauge_pair_ble_scan_stop();
            } else {
                elm327_ble_scan_only_stop();
            }
            lv_indev_wait_release(lv_indev_get_act());
            ui_menu_open();   // opened from the menu (OBD): back to it
        }
    }
}

