// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: OBD_PRJ

#ifndef _OBD_PRJ_UI_H
#define _OBD_PRJ_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_events.h"
#include "ui_disp_item.h"
#include "ui_theme.h"
#include "esp_log.h"
#include "app_obd_dsp/obd_data_cache.h"


#define COLOR_MITSUBISHI_RED    0xFFFFFF //main color white (originally Mitsubishi red)
#define COLOR_DOMIANT_PINK      0xFFFFFF //main color white (originally pink)
#define COLOR_SECONDARY_PINK    0x333333 //secondary color dark gray (originally dark pink)



void ui_ScreenPageLogo_screen_init(void);
extern lv_obj_t * ui_ScreenPageLogo;
extern lv_obj_t * imageLogo;

// SCREEN: ui_ScreenPageThemeGauge (theme-partition gauge page: the gauge itself)
void ui_ScreenPageThemeGauge_screen_init(void);
extern lv_obj_t * ui_ScreenPageThemeGauge;
void ui_event_theme_gauge_background(lv_event_t * e);
void ui_event_theme_gauge_long_press(lv_event_t * e);
void ui_theme_delete_prompt(void);
void ui_theme_page_touch_through(lv_obj_t *obj);
extern lv_obj_t *ui_ScreenPageGames;      // GAMES page (screens/game_core.c)
void ui_ScreenPageGames_screen_init(void);
extern uint8_t ui_theme_gauge_page_index;  // Current theme page index

// SCREEN: ui_ScreenPageEasterEgg (VERSION: device info)
void ui_ScreenPageEasterEgg_screen_init(void);
extern lv_obj_t * ui_ScreenPageEasterEgg;
extern lv_obj_t * imageEasterEgg;
extern lv_obj_t * ui_LabelEasterEggInfo;  // dynamically updated device info label
void ui_event_easter_egg_ota_button(lv_event_t * e);  // OTA mode button handler

// SCREEN: ui_ScreenPageBLEScan (OBD: pick the adapter)
void ui_ScreenPageBLEScan_screen_init(void);
extern lv_obj_t * ui_ScreenPageBLEScan;
void ui_event_ble_scan_background(lv_event_t * e);

// SCREEN: ui_ScreenPageOTAMode (UPDATE)
void ui_ScreenPageOTAMode_screen_init(void);
extern lv_obj_t * ui_ScreenPageOTAMode;
void ui_device_info_refresh(void);   // device info page (screens/ui_ScreenPageEasterEgg.c)
extern lv_obj_t * ui_LabelOTAModeStatus;
extern lv_obj_t * ui_LabelOTAModeVersion;
void ui_ota_mode_refresh(void);  // called from timer to update OTA status

// Boot animation progress sync (ESP-NOW): master broadcasts / slaves follow
int  ui_intro_get_step(void);
void ui_intro_set_step(int step);
int  ui_sweep_get_step(void);       // get the current sweep progress (master broadcasts to slaves)
// Data-item accessors (ui_disp_item_name/unit/color/range) — see ui_disp_item.h

// IMAGES AND IMAGE SETS
const lv_img_dsc_t *imgBootLogoCustom_get(void);   // the Racing My Car logo, 360x360 (boot), inflated on first use; NULL if it cannot be
LV_IMG_DECLARE(imgRmcMarkSmall);        // small yellow Racing My Car mark (menu, info page)

// RPM warning: flash state (ui_ext.c)
extern volatile int s_rpm_flash_test_ticks;

// Sweep sync from the master gauge (ESP-NOW)
void ui_sweep_set_from_sync(int sweep_step);
// FONTS
LV_FONT_DECLARE(ui_font_FontTypoderSize16);
LV_FONT_DECLARE(ui_font_FontTypoderSize20);
LV_FONT_DECLARE(ui_font_FontTypoderSize24);
LV_FONT_DECLARE(ui_font_FontTypoderSize36);
LV_FONT_DECLARE(ui_font_FontTypoderSize44);
LV_FONT_DECLARE(ui_font_FontTypoderSize56);
LV_FONT_DECLARE(ui_font_FontTypoderSize140);


// UI INIT
void ui_init(void);
void ui_event_logo_background(lv_event_t * e);
void ui_event_easter_egg_background(lv_event_t * e);
#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
